# Generated by Django 5.2.17 on 2026-08-05 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
        ('lessons', '0001_initial'),
        ('quizzes', '0002_studentanswer_topic_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mastery_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_questions_answered', models.PositiveIntegerField(default=0)),
                ('total_correct_answers', models.PositiveIntegerField(default=0)),
                ('total_points_earned', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_points_possible', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('recent_accuracy', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('difficulty_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('consistency_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('independent_score', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('status', models.CharField(choices=[('NEEDS_SUPPORT', 'Needs Support'), ('DEVELOPING', 'Developing'), ('PROFICIENT', 'Proficient'), ('MASTERED', 'Mastered')], default='NEEDS_SUPPORT', max_length=20)),
                ('first_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('last_recalculated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topic_masteries', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topic_masteries', to='curriculum.curriculumtopic')),
            ],
            options={
                'ordering': ['-mastery_score', 'topic__title'],
            },
        ),
        migrations.CreateModel(
            name='MasteryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('new_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('score_change', models.DecimalField(decimal_places=2, max_digits=6)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quiz_attempt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mastery_histories', to='quizzes.quizattempt')),
                ('topic_mastery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='progress.topicmastery')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('REVIEW_LESSON', 'Review Lesson'), ('EASY_PRACTICE', 'Easy Practice'), ('GUIDED_PRACTICE', 'Guided Practice'), ('MIXED_PRACTICE', 'Mixed Practice'), ('ADVANCE_TOPIC', 'Advance Topic'), ('SPACED_REVIEW', 'Spaced Review')], max_length=20)),
                ('priority', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('DISMISSED', 'Dismissed'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_from_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recommendations', to='quizzes.quizattempt')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
                ('target_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recommendations', to='lessons.lesson')),
                ('target_quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recommendations', to='quizzes.quiz')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recommendations', to='curriculum.curriculumtopic')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['student', 'status'], name='progress_re_student_bee235_idx'), models.Index(fields=['student', 'topic'], name='progress_re_student_3f0cb5_idx'), models.Index(fields=['topic', 'status'], name='progress_re_topic_i_ca2fd3_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('student', 'topic', 'recommendation_type'), name='unique_active_recommendation_per_student_topic_type')],
            },
        ),
        migrations.AddIndex(
            model_name='topicmastery',
            index=models.Index(fields=['student', 'status'], name='progress_to_student_4f62a8_idx'),
        ),
        migrations.AddIndex(
            model_name='topicmastery',
            index=models.Index(fields=['topic', 'status'], name='progress_to_topic_i_6262a2_idx'),
        ),
        migrations.AddConstraint(
            model_name='topicmastery',
            constraint=models.UniqueConstraint(fields=('student', 'topic'), name='unique_student_topic_mastery'),
        ),
        migrations.AddConstraint(
            model_name='topicmastery',
            constraint=models.CheckConstraint(condition=models.Q(('mastery_score__gte', 0), ('mastery_score__lte', 100)), name='progress_mastery_score_between_0_and_100'),
        ),
        migrations.AddConstraint(
            model_name='topicmastery',
            constraint=models.CheckConstraint(condition=models.Q(('total_questions_answered__gte', 0)), name='progress_total_questions_answered_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='topicmastery',
            constraint=models.CheckConstraint(condition=models.Q(('total_correct_answers__gte', 0)), name='progress_total_correct_answers_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='topicmastery',
            constraint=models.CheckConstraint(condition=models.Q(('total_points_earned__gte', 0)), name='progress_total_points_earned_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='topicmastery',
            constraint=models.CheckConstraint(condition=models.Q(('total_points_possible__gte', 0)), name='progress_total_points_possible_non_negative'),
        ),
        migrations.AddIndex(
            model_name='masteryhistory',
            index=models.Index(fields=['topic_mastery', 'created_at'], name='progress_ma_topic_m_a2d7e1_idx'),
        ),
        migrations.AddIndex(
            model_name='masteryhistory',
            index=models.Index(fields=['quiz_attempt'], name='progress_ma_quiz_at_b9f951_idx'),
        ),
        migrations.AddConstraint(
            model_name='masteryhistory',
            constraint=models.UniqueConstraint(fields=('topic_mastery', 'quiz_attempt'), name='unique_history_per_topic_mastery_and_attempt'),
        ),
    ]
