from django.urls import path

from apps.quizzes.views import (
    AnswerSaveView,
    AttemptDetailView,
    AttemptResultsView,
    AttemptSubmitView,
    ChoiceDetailView,
    ClassroomQuizResultsView,
    MyAttemptsView,
    MyQuizzesView,
    QuestionApproveView,
    QuestionChoiceListCreateView,
    QuestionDetailView,
    QuestionRejectView,
    QuizArchiveView,
    QuizAttemptsView,
    QuizDetailView,
    QuizListCreateView,
    QuizPublishView,
    QuizQuestionListCreateView,
    QuizResultsSummaryView,
)

urlpatterns = [
    path("quizzes/", QuizListCreateView.as_view(), name="quiz-list"),
    path("quizzes/<int:pk>/", QuizDetailView.as_view(), name="quiz-detail"),
    path("quizzes/<int:pk>/publish/", QuizPublishView.as_view(), name="quiz-publish"),
    path("quizzes/<int:pk>/archive/", QuizArchiveView.as_view(), name="quiz-archive"),
    path("quizzes/<int:pk>/questions/", QuizQuestionListCreateView.as_view(), name="quiz-questions"),
    path("quizzes/<int:pk>/attempts/", QuizAttemptsView.as_view(), name="quiz-attempts"),
    path("quizzes/<int:pk>/results-summary/", QuizResultsSummaryView.as_view(), name="quiz-results-summary"),
    path("questions/<int:pk>/", QuestionDetailView.as_view(), name="question-detail"),
    path("questions/<int:pk>/approve/", QuestionApproveView.as_view(), name="question-approve"),
    path("questions/<int:pk>/reject/", QuestionRejectView.as_view(), name="question-reject"),
    path("questions/<int:pk>/choices/", QuestionChoiceListCreateView.as_view(), name="question-choices"),
    path("choices/<int:pk>/", ChoiceDetailView.as_view(), name="choice-detail"),
    path("attempts/<int:pk>/", AttemptDetailView.as_view(), name="attempt-detail"),
    path(
        "attempts/<int:pk>/answers/<int:question_id>/",
        AnswerSaveView.as_view(),
        name="attempt-answer",
    ),
    path("attempts/<int:pk>/submit/", AttemptSubmitView.as_view(), name="attempt-submit"),
    path("attempts/<int:pk>/results/", AttemptResultsView.as_view(), name="attempt-results"),
    path("students/me/attempts/", MyAttemptsView.as_view(), name="my-attempts"),
    path("students/me/quizzes/", MyQuizzesView.as_view(), name="my-quizzes"),
    path("classrooms/<int:pk>/quiz-results/", ClassroomQuizResultsView.as_view(), name="classroom-quiz-results"),
]