# Generated by Django 5.2.17 on 2026-08-05 07:03

import django.db.models.deletion
from django.db import migrations, models


def backfill_answer_topics(apps, schema_editor):
    StudentAnswer = apps.get_model("quizzes", "StudentAnswer")
    for answer in StudentAnswer.objects.select_related("question").filter(topic__isnull=True):
        if answer.question.topic_id is not None:
            answer.topic_id = answer.question.topic_id
            answer.save(update_fields=["topic"])


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_answers', to='curriculum.curriculumtopic'),
        ),
        migrations.RunPython(backfill_answer_topics, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='studentanswer',
            index=models.Index(fields=['topic'], name='quizzes_stu_topic_i_e7de73_idx'),
        ),
    ]
