# Generated by Django 5.2.17 on 2026-08-04 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classrooms', '0001_initial'),
        ('curriculum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('learning_objectives', models.JSONField(blank=True, default=list)),
                ('content', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to=settings.AUTH_USER_MODEL)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='classrooms.classroom')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='curriculum.curriculumtopic')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['classroom', 'status'], name='lessons_les_classro_9728e9_idx'), models.Index(fields=['topic', 'status'], name='lessons_les_topic_i_0ac12e_idx'), models.Index(fields=['author', 'status'], name='lessons_les_author__69ccb2_idx')],
            },
        ),
    ]
